#!/bin/bash
echo "╔════════════════════════════════════════════════════════════╗"
echo "║        Imperium System Status - Raspberry Pi              ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "📍 Platform: $(cat /etc/os-release | grep PRETTY_NAME | cut -d'"' -f2)"
echo "🐍 Python: $(python3 --version)"
echo ""
echo "--- Docker Services ---"
docker compose ps --format "table {{.Service}}\t{{.Status}}\t{{.Ports}}" 2>/dev/null || echo "Docker not running"
echo ""
echo "--- Python Environment ---"
source venv/bin/activate 2>/dev/null
echo "✓ Virtual environment: $(which python)"
echo "✓ Packages installed: $(pip list 2>/dev/null | wc -l) packages"
echo ""
echo "--- System Files ---"
[ -f .env ] && echo "✓ Configuration: .env exists" || echo "✗ Configuration: .env missing"
[ -f data/imperium.db ] && echo "✓ Database: $(ls -lh data/imperium.db | awk '{print $5}')" || echo "✗ Database: Not initialized"
[ -d venv ] && echo "✓ Virtual env: venv/" || echo "✗ Virtual env: Missing"
echo ""
echo "--- Network Tools ---"
tc -Version 2>&1 | head -1
echo "✓ iptables: $(which iptables)"
echo ""
echo "--- Service URLs ---"
echo "   API:        http://$(hostname):5000"
echo "   Grafana:    http://$(hostname):3000"
echo "   Prometheus: http://$(hostname):9090"
echo ""
echo "--- Quick Start Commands ---"
echo "   Start API:    source venv/bin/activate && PYTHONPATH=$(pwd) python src/main.py"
echo "   Systemd:      sudo systemctl start imperium"
echo "   Test Health:  curl http://localhost:5000/health"
echo ""
